name: Monitor Student Progress

on:
  push:
    branches:
      - '*'

jobs:
  track_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify commit
        run: |
          echo "Commit detected on branch: ${{ github.ref }}"
          echo "Commit made by: ${{ github.actor }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
