name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ubah versi python yang valid

      - name: Skip installing dependencies (no requirements.txt needed)
        run: echo "No dependencies"

      - name: Run tests
        run: |
          pytest  # Atau framework testing lain yang digunakan
